version: '3.9'

services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=sqlite:///data/app.db
    volumes:
      - ./backend/data:/app/data
    ports:
      - '8000:8000'

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_USE_MOCK=false
      - VITE_API_BASE=/api/v1
      - VITE_PROXY_TARGET=http://backend:8000
    ports:
      - '5173:5173'
    depends_on:
      - backend
