version: '3.9'

services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=sqlite:///data/app.db
    volumes:
      - ./backend/data:/app/data
    ports:
      - '8000:8000'

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_USE_MOCK=false
      - VITE_API_BASE=/api/v1
      - VITE_PROXY_TARGET=http://backend:8000
    ports:
      - '5173:5173'
    depends_on:
      - backend
      - minio

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-change-me}
    volumes:
      - ./minio/data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
