model:
  base_id: stabilityai/stable-diffusion-xl-base-1.0
  use_ip_adapter: true
  use_controlnet: true
  height: 1024
  width: 1024
  steps: 30
  guidance: 7.5
  negative_prompt: "low quality, out of focus, distorted anatomy, caricature"
  ip_adapter:
    weight_path: null
    weight_name: null
    subfolder: null
    weight: 0.7
  controlnet:
    union_path: null
    depth_path: null
    pose_path: null
    edge_path: null
consistency:
  seed: 12345
  img2img_strength: 0.55
  face_crop_size: 512
  ip_adapter_weight: 0.8
  controlnet_weight: 0.9
  controlnet_use:
    depth: false
    pose: false
    edges: true
thresholds:
  identity_min: 0.85
  ssim_min: 0.8
  lpips_max: 0.3
  scene_diversity_min: 0.15
evaluation:
  clip_model: "openai/clip-vit-large-patch14"
  dreamsim_model: "kandinsky-community/dreamsim"
logging:
  level: INFO
